[build]
  publish = "."

[[redirects]]
  from = "/dashboard"
  to = "/Dashboard/index.html"
  status = 200

[[redirects]]
  from = "/dashboard/*"
  to = "/Dashboard/:splat"
  status = 200

[[redirects]]
  from = "/coach"
  to = "/Coach/index.html"
  status = 200

[[redirects]]
  from = "/coach/*"
  to = "/Coach/:splat"
  status = 200

[[redirects]]
  from = "/assessment"
  to = "/Assessment/index.html"
  status = 200

[[redirects]]
  from = "/pricing"
  to = "/Pricing/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
